export const devIcons = [
  { iconName: 'devicon-html5-plain', name: 'HTML' },
  { iconName: 'devicon-css3-plain', name: 'CSS' },
  { iconName: 'devicon-javascript-plain', name: 'JavaScript' },
  { iconName: 'devicon-figma-plain', name: 'Figma' },
  { iconName: 'devicon-canva-plain', name: 'Canva' },
  { iconName: 'devicon-windows8-plain', name: 'PowerPoint' },
  { iconName: 'devicon-windows8-plain', name: 'Excel' },
  { iconName: 'devicon-windows8-plain', name: 'Word' },
  { iconName: 'devicon-windows8-plain', name: 'Power BI' },
  { iconName: 'devicon-mysql-plain', name: 'SQL' },   
  { iconName: 'devicon-python-plain', name: 'Python' },  
  { iconName: 'devicon-laravel-plain', name: 'Laravel' },  
  { iconName: 'devicon-rstudio-plain', name: 'R' },  
  ]  
